apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deploy
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: webpod
          image: imgname
          ports:
            - containerPort: 5000
         
